### ISSUE TITLE
Bumping into "type initializer for 'Fable.Core.JS' threw an exception."

### ISSUE THREAD

**Issue by chgeuer** [njlr/thoth-json-codec#2]
Hi @njlr, 

your library looks very interesting, would love to use it to clean up my approach [here](https://github.com/microsoft/metered-billing-accelerator/blob/main/src/Metering.BaseTypes/Json.fs)... 

However, I'm having basic challenges understanding how to use it. I'm not building a web app, or use Fable, or anything, just trying to spit out some JSON in a console app. 

My `.fsproj` is comparably simple (even though I'm not sure I need `Newtonsoft.Json`.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Thoth.Json.Codec" Version="0.0.3" />
  </ItemGroup>
</Project>
```

In my `Program.fs`, I do this:

```fsharp
open Thoth.Json
open Thoth.Json.Codec

123
|> Encode.codec Codec.int
|> Encode.toString 2
|> printfn "%s"
```

Which brings me that:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Fable.Core.JS' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$Fable-Core>.$Fable.Core.JS' threw an exception.
 ---> System.Exception: JS only
   at <StartupCode$Fable-Core>.$Fable.Core.JS..cctor()
   --- End of inner exception stack trace ---
   at Fable.Core.JS..cctor()
   --- End of inner exception stack trace ---
   at Thoth.Json.Encode.toString(Int32 space, Object value)
   at <StartupCode$ConsoleApp1>.$Program.main@() in ConsoleApp1\Program.fs:line 6
```

**Comment by chgeuer** [comment]
Apologies, this is for sure not a problem in your library, just my ignorance to the F# ecosystem...

**Comment by njlr** [comment]
Hi @chgeuer 

Nope, it's an issue with this package!

Currently it only works for Fable projects. I haven't had a moment to create a .NET version or to figure out universal packaging yet. 

Let me try to figure something out...

Related discussion: https://github.com/fable-compiler/Fable/issues/2953

**Comment by njlr** [comment]
There is now a .NET version of the package! :package: 

`Scratch.fsx`

```fsharp
#r "nuget: Thoth.Json.Net.Codec"

open Thoth.Json.Net
open Thoth.Json.Net.Codec

123
|> Encode.codec Codec.int
|> Encode.toString 2
|> printfn "%s"
```

```bash
$ dotnet fsi ./Scratch.fsx
123
```

**Comment by chgeuer** [comment]
Nice, the sample works, that help a lot to assess for my larger project ❤️
